version: "3"

services:
    php:
        container_name: php
        depends_on:
            - postgres
        restart: always
        build: docker/php
        working_dir: /usr/share/nginx/html
        volumes:
            - ./docker/php/conf.d:$PHP_INI_DIR/conf.d
            - .:/usr/share/nginx/html

    nginx:
        container_name: nginx
        depends_on:
            - php
        restart: always
        image: nginx:latest
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - .:/usr/share/nginx/html
        ports:
            - 80:80

    postgres:
        container_name: postgres
        restart: always
        image: postgres:latest
        volumes:
            - ./database:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=user
            - POSTGRES_DB=gandi
            - PGDATA=/var/lib/postgresql/data
        ports:
            - 5432:5432

    adminer:
        container_name: adminer
        depends_on:
            - postgres
        restart: always
        image: adminer:latest
        ports:
            - 8080:8080

    composer:
        container_name: composer
        build:
            context: docker/php
            dockerfile: Dockerfile
        entrypoint: composer
        volumes:
            - .:/home/user
